scan_timeout = 60
add_newline = true

[character]
format = " \n$symbol"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol = "[V](bold green) "

[line_break]
disabled = true

[directory]
format = "[$path]($style) "
style = "bold yellow"
truncation_length = 8
use_os_path_sep = true

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

[sudo]
format = "[$symbol]($style)"
style = "bold red"
symbol = " "

[deno]
format = "[🦕$version](green bold) "

[scala]
symbol = '[ $version](red bold) '

[aws]
format = 'on [$symbol $profile ()]($style) '
style = 'bold organ'
symbol = '☁️ '
[aws.profile_aliases]
Enterprise_Naming_Scheme-voidstars = 'void**'

